### ISSUE TITLE
Page-to-Blogpost Macro not working with Atlassian's Documentation Theme

### ISSUE THREAD

**Issue by garmccor** [chris-kent/Confluence-Blog-Tools#14]
We have built a page templates in a space, and relied on the {page to blogpost} macro to automate the page's conversion into a blog post, then delete the original page, once the page template has been published.

Before we switched the theme to the Documentation Theme, this function worked perfectly (kudos!), but now it looks like it isn't working as intended. We have also recently updated Confluence to 5.10.7 (server), but I am 90% sure the macro worked with this version before we switched the theme.

Steps to reproduce:
1. Use "Blog FAQ" Template to open page creator in the "Support" space of Confluence
2. Publish your page
3. Page continues to exist (isn't deleted)
4. Locate blogpost, with unclean title (see screenshot)

<img width="790" alt="screen shot 2016-12-13 at 1 10 48 pm" src="https://cloud.githubusercontent.com/assets/4674846/21159322/a57c94b0-c135-11e6-8eb5-77d7f8dce12b.png">

**Comment by chris-kent** [comment]
Hi there

Can you please install the latest version of the Plugin for your confluence
version.

I believe this issue had been fixed.

After you install this please let me know if you still have this problem

Cheers

On 14 Dec 2016 8:11 AM, "garmccor" <notifications@github.com> wrote:

We have built a page templates in a space, and relied on the {page to
blogpost} macro to automate the page's conversion into a blog post, then
delete the original page, once the page template has been published.

Before we switched the theme to the Documentation Theme, this function
worked perfectly (kudos!), but now it looks like it isn't working as
intended. We have also recently updated Confluence to 5.10.7 (server), but
I am 90% sure the macro worked with this version before we switched the
theme.

Steps to reproduce:

   1. Use "Blog FAQ" Template to open page creator in the "Support" space
   of Confluence
   2. Publish your page
   3. Page continues to exist (isn't deleted)
   4. Locate blogpost, with unclean title (see screenshot)

[image: screen shot 2016-12-13 at 1 10 48 pm]
<https://cloud.githubusercontent.com/assets/4674846/21159322/a57c94b0-c135-11e6-8eb5-77d7f8dce12b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chris-kent/Confluence-Blog-Tools/issues/14>, or mute
the thread

**Comment by bberen-uber** [comment]
We are already using 3.4

**Comment by chris-kent** [comment]
That is interesting, as the new version does not use those temporary pages "pagetoblog-xxxxxx-"
I will need to investigate, so to confirm you have the following versions
Confluence 5.10.7
Blog Tools 3.4
Cheers
Chris

**Comment by bberen-uber** [comment]
That is correct.

**Comment by garmccor** [comment]
@bberen-uber I just updated to 3.4 at 1:30 PST

**Comment by DerekSarshad** [comment]
Hey guys, 

Since the update to 3.4, I've used a page template that has the page-to-blogpost macro on it, and it still doesn't seem to be working in our production environment:

If there's anything I can do to help trouble shoot, please let me know!

Please, see the attached screenshots:

**Drafted page with macro:**
![1 draft page](https://cloud.githubusercontent.com/assets/24597890/21248321/202aa34e-c2eb-11e6-81c5-38042819f7b2.png)

**Published page:**
![2 published page](https://cloud.githubusercontent.com/assets/24597890/21248322/202b6ee6-c2eb-11e6-85fd-e32a06df7add.png)

**Page doesn't appear to have been converted and published as a blog post:**
![3 blost post is absent](https://cloud.githubusercontent.com/assets/24597890/21248320/20293586-c2eb-11e6-9edc-3918de55780e.png)

**Comment by chris-kent** [comment]
Hi guys,

Sorry for the late reply, I have been on holidays.

Can you please turn on logging for "net.kentcom" component in the administrator section of Confluence and send me all the matching lines in the log file.

Thanks
Chris

**Comment by bberen-uber** [comment]
I have done that, but with some further testing I can't actually reproduce
the user perceived behavior anymore. I am going to go back to the end user
to get more information.

Boris

**Comment by bberen-uber** [comment]
Ok so I have been doing more digging into this and the issue does continue
to reproduce. Using version 3.4 of the add-on, the logs are:

2017-01-03 20:34:55,804 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] pageCreateFromTemplateEvent
com.atlassian.confluence.event.events.content.page.PageCreateFromTemplateEvent@4c8de292[templateId=85426239,page=page:
asdsada v.1 (139659855),suppressNotifications=false,timestamp=1483475695804]
2017-01-03 20:34:55,809 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.LicenseCheck] isLicenseOK Check License
2017-01-03 20:34:55,812 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro details
2017-01-03 20:34:55,814 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro column
2017-01-03 20:34:55,815 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro toc
2017-01-03 20:34:55,815 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro column
2017-01-03 20:34:55,816 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro section
2017-01-03 20:34:55,817 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro excerpt
2017-01-03 20:34:55,818 INFO [http-nio-8090-exec-18]
[net.kentcom.blogtools.PageToBlogListener] replace Found Macro
page-to-blog-macro

Any suggestions on how to proceed? net.kentcom has been placed into ALL (no
change from DEBUG in terms of contents) in the logging and profiling
portion of the Confluence admin UI.

Best,
Boris

**Comment by bberen-uber** [comment]
I just wanted to follow up on this and see what we should be doing?

**Comment by chris-kent** [comment]
Hi there,
Just touching base, I have been in contact with Atlassian and they have provided me with the new implementation of the JS side of handling new pages via templates.
I am trying to get this working, not that easy, and this could be the reason why the plugin has glitches with the new versions of Confluence.
I'll be in touch when I have more to share.
P.S I am assuming that the plugin is mostly usable, and likely only affected by slow networking?
Cheers
Chris

**Comment by bberen-uber** [comment]
The macro functionality is 100% not working. The manual conversion works
consistently.

Boris

**Comment by chris-kent** [comment]
I have made some improvements in version 3.5, hopefully all your issues are fixed :)

**Comment by lrogana** [comment]
Hi Chris, This seems to still be a problem. I had sent you an email a while ago but following up on this. I have the latest version and still can't convert a page to a blog when inserting the macro. 
Is the macro functionality supposed to be working? 
Thanks

**Comment by chris-kent** [comment]
Hi lrogana,

I am so sorry, I have looked everywhere for your email and I can't find it.

Can you please describe what the issue is? I assume it is not the problem raised above in this issue, as that code is no longer in the plugin. I no longer create temporary pages....

1.Please tell me the versions of both Confluence and the plugin.
2.Describe the steps to reproduce the problem.
3.Then turn on logging in the Logging and Profiling admin section set net.kentcom = ALL.
execute the steps to reprocuce the error and then send me the snippet from the log file that matches the error and then I can look further into this problem.

Thanks
Chris

**Comment by lrogana** [comment]
Hey Chris, 
Thanks for getting back to me on this so my assumption is the macro is supposed to automatically do the manual steps of converting the page to blog. 
1. Our production environment is on Confluence 5.10.8 and plugin version 3.11. I am experiencing the same behavior in a test box with confluence 6.2.1.
2. The steps are basically include the macro on a page. 
3. 
This is when I manually convert a page to blog. This works just fine and here are the logs. 

2017-06-08 14:22:09,956 INFO [http-nio-8090-exec-4] [net.kentcom.blogtools.PageToBlogListener] getMetaDataManager MetaData plugin loaded: false
2017-06-08 14:22:09,957 INFO [http-nio-8090-exec-4] [net.kentcom.blogtools.PageToBlogListener] copyMetadata Could not get a valid MetadataManager.
2017-06-08 14:22:09,958 INFO [http-nio-8090-exec-4] [net.kentcom.blogtools.PageToBlogListener] convertPageToBlog End of convertPageToBlog
2017-06-08 14:22:09,959 INFO [http-nio-8090-exec-4] [net.kentcom.blogtools.PageToBlogServlet] doPost New blog  blogpost: Blank Page to Try and Convert  to Blog v.1 (983045)
2017-06-08 14:22:09,960 INFO [http-nio-8090-exec-4] [net.kentcom.blogtools.PageToBlogServlet] doPost Deleting Page: page: Blank Page to Try and Convert  to Blog v.1 (983043)
2017-06-08 14:22:10,050 WARN [http-nio-8090-exec-4] [hql.internal.ast.HqlSqlWalker] generatePositionalParameter [DEPRECATION] Encountered positional parameter near line 1, column 112 in HQL: [from com.atlassian.confluence.internal.relations.dao.Content2ContentRelationEntity re where re.sourceContent = ? OR re.targetContent = ?].  Positional parameter are considered deprecated; use named parameters or JPA-style positional parameters instead.
 -- referer: http://172.28.128.5:8090/display/DATA/Blank+Page+to+Try+and+Convert++to+Blog | url: /plugins/servlet/pageToBlogServlet | traceId: 9c72705a837d31bd | userName: admin
2017-06-08 14:22:10,052 WARN [http-nio-8090-exec-4] [hql.internal.ast.HqlSqlWalker] generatePositionalParameter [DEPRECATION] Encountered positional parameter near line 1, column 136 in HQL: [from com.atlassian.confluence.internal.relations.dao.Content2ContentRelationEntity re where re.sourceContent = ? OR re.targetContent = ?].  Positional parameter are considered deprecated; use named parameters or JPA-style positional parameters instead.
 -- referer: http://172.28.128.5:8090/display/DATA/Blank+Page+to+Try+and+Convert++to+Blog | url: /plugins/servlet/pageToBlogServlet | traceId: 9c72705a837d31bd | userName: admin
2017-06-08 14:22:10,057 WARN [http-nio-8090-exec-4] [hql.internal.ast.HqlSqlWalker] generatePositionalParameter [DEPRECATION] Encountered positional parameter near line 1, column 109 in HQL: [from com.atlassian.confluence.internal.relations.dao.User2ContentRelationEntity re where re.targetContent = ?].  Positional parameter are considered deprecated; use named parameters or JPA-style positional parameters instead.
 -- referer: http://172.28.128.5:8090/display/DATA/Blank+Page+to+Try+and+Convert++to+Blog | url: /plugins/servlet/pageToBlogServlet | traceId: 9c72705a837d31bd | userName: admin
2017-06-08 14:22:10,063 WARN [http-nio-8090-exec-4] [hql.internal.ast.HqlSqlWalker] generatePositionalParameter [DEPRECATION] Encountered positional parameter near line 1, column 128 in HQL: [from com.atlassian.confluence.internal.relations.dao.User2ContentRelationEntity re where re.targetContent.originalVersion.id = ? and re.targetContent.contentStatus = 'current'].  Positional parameter are considered deprecated; use named parameters or JPA-style positional parameters instead.
 -- referer: http://172.28.128.5:8090/display/DATA/Blank+Page+to+Try+and+Convert++to+Blog | url: /plugins/servlet/pageToBlogServlet | traceId: 9c72705a837d31bd | userName: admin


No logs are returned when I add a macro to a page and save or publish the page. 

Also when I add a macro to a page and try to preview nothing is returned. 
<img width="1410" alt="screen shot 2017-06-08 at 7 27 04 am" src="https://user-images.githubusercontent.com/2373601/26934522-7736c87c-4c1e-11e7-8f0e-f4268555675c.png">

<img width="906" alt="screen shot 2017-06-08 at 7 27 14 am" src="https://user-images.githubusercontent.com/2373601/26934488-5feeb21a-4c1e-11e7-8bfb-c2e65aaa4528.png">

**Comment by chris-kent** [comment]
Hi,

Firstly, in Edit page and you edit the Macro, it actually does nothing, it has nothing to render. I use the Macro as a trigger only, so the fact you see nothing in the preview is understandable.

On the main issue, my guess now is that it is actually related to the Theme. By any chance are you using a third party theme plugin?

Thanks to Atlassian, the only way to detect when pages are created from templates is from the html on the page.  It now sounds very much like the html tag I am looking for is not available in your system for some reason.

Is there any chance that you can send me the html content of your page, after you trigger the **Create** page from template action, but before you publish.  If you are familiar with debugging Chrome, then follow these steps:
1. press F12
2. then in the debug window toolbar, select Elements
3. then right click on the <html> tag at the top
4. then select Copy
5. then select Copy element

Paste the results back into an email. This will help me diagnose why the macro is not triggering the conversion.

Thanks
Chris

**Comment by lrogana** [comment]
Hey Chris, 
No theme this is a totally new instance on my vm that I started to try and troubleshoot this issue without having to consider other factors. 
I sent the email of the copied element to your gmail. I hope that is the correct email. 

Liston

**Comment by chris-kent** [comment]
HI there,

I did not receive the attachment. You can either send it direct to my gmail
account, or you will need to send it from github by attaching it to the
issue, then I will get it.

Thanks
Chris

**Comment by lrogana** [comment]
Here you go. 
[testingTemplate.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1065575/testingTemplate.txt)

**Comment by chris-kent** [comment]
Ok got it. I'll take a look and hopefully find out what is wrong.

**Comment by chris-kent** [comment]
Hmm, Well there was nothing wrong with the html.

Next, can you again open the browser debugger (F12).
Then click on the console (in the debugger menu)
Clear the console (CTRL-L)
Then click Create Page from template.
Once the Editor is shown (before any page refresh occurs)
Right Click in the console window and select Save AS.
There should be some logging in here to show that the macro has triggered,
save this file.
Then the next part might be tricky, click the Publish (or Save) button, and
try to capture the console before the page refreshes. Don't stress too much
if you can't, the main trigger is activated when the template editor loads
the page to edit.

Thanks
Chris

**Comment by chris-kent** [comment]
Hi,

I had another thought, it could be the javascript code, which may be not
working correctly which sometimes behaves differently on browsers .

Please tell me which browser and version you are using? If not Chrome, any
chance you can try it in Chrome.

Cheers
Chris

**Comment by lrogana** [comment]
I am using chrome.

**Comment by chris-kent** [comment]
Ok thanks.
I would like to see the Web console log. If you can grab that then i might
be able to get a better picture of what is not triggering the conversion.
Cheers
Chris

**Comment by lrogana** [comment]
Hello, 
Attached is the web console logs. 

Liston

**Comment by chris-kent** [comment]
Hi Liston,

Thanks for the last log. This has enabled me to find the fault in the
process.

I can see that when you "Publish" a page from the template, I do not get
back a successful save message from Confluence. If I don't get a Save
message, then I don't perform the conversion, because I don't know if the
page is ready, or what it's page id is etc...

Although I know this information, I have no idea why this happens in your
system, this is odd.
By any chance, do you have slow network, or network issues?
Do all your Saves and Published pages work OK? Do you often find that pages
hang after you Save?

I'll have to raise an issue/ticket with Atlassian for further advice on
this matter.

I have also tested this on a Production system with the same versions, and
this works for me without any issues.

Is there anything else special or different in your system setup that may
help?

Otherwise, I don't believe I will be able to fix this, unless Atlassian can
offer some info when I raise a ticket.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,

I have atlassian looking into this, they have asked a couple of questions.


1.  in chrome dev tools and there's an error icon indicated
2.  can your customer try it in incognito mode or anything cache cleared?

Also, after further investigation on the console log you provided, I see
that a conversion attempt was actually made. I did not see this earlier as
there are about 400 lines of logging between the detection of the template
and the execution of the conversion. By any chance, can you also redo this
test and grab both the console log and backend confluence log for the same
attempt?

**Comment by lrogana** [comment]
Incognito mode is the same issue. Attached is console and confluence logs. 
[confluencelogs.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1080833/confluencelogs.txt)
[consolelogs.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1080832/consolelogs.txt)

**Comment by chris-kent** [comment]
Hi,

Did you enable net.kentcom logging on the backend?

But anyway, what I can see from the console log, it actually worked. 

Here are snippets which tell me everything is working as expected... my logging shows all the steps are doing what I expect... even the last one tells me the browser is redirected to the new blog post...

:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 Create Form
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 Page Template or Page Draft
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 Converting this Page to BLOGPOST

....

:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 onSuccessfulResponse
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 Page ID: 1900546
batch.js:633 Stop heartbeat activity on page id 1900546
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 /display/TEST/Testing+Blog
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 Now converting to Blog, checking License
:8090/s/92cfa851637585a134adb16bb82dc923-CDN/en_GB/7111/a907385b66baaca0231…dministrator=true&locale=en-GB&nps-acknowledged=true&nps-enabled=true:7448 License OK, now converting
Navigated to http://172.28.128.5:8090/display/TEST/2017/06/16/Testing+Blog

From this trace, am I to understand that the blog display/TEST/2017/06/16/Testing+Blog does not actually exist?

This may tell me that the backend is doing it's stuff, but possibly failing to actually save the blog post. I don't understand this, can you please confirm if net.kentcom logging was on? if so, then I'll send this off to Atlassian to analyse, but the fact I see no logging, but it worked is very odd.

Chris

**Comment by lrogana** [comment]
For some reason I thought it was on. Turned it on for my localhost. here is the logs. 
[bloglogs.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1080962/bloglogs.txt)

**Comment by chris-kent** [comment]
OK, that looks great, I assume there are no exception dumps anywhere in logging that you trimmed out?

So, from that log and the console log, I don't know what is wrong?

From the earlier one, is this link valid? http://172.28.128.5:8090/display/TEST/2017/06/16/Testing+Blog

**Comment by lrogana** [comment]
If you have time I think we should get on a call.

**Comment by lrogana** [comment]
The link is valid.

**Comment by chris-kent** [comment]
I was just about to go to bed, but I would love to see what is going on as well :)
Do you have skype?

**Comment by chris-kent** [comment]
You can send me an invite to chris.kent@ir.com, either skype or gotomeeting or whatever you use

**Comment by lrogana** [comment]
Hey Chris, 
Thanks for taking the time to join the call. I have attached the logs as we discussed. 
Liston 
[staginginstance.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1081124/staginginstance.txt)
