### ISSUE TITLE
Notifications from restricted blog posts

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#27]
Hi Chris,

since closing the [issue 21](https://github.com/chris-kent/Confluence-Blog-Tools/issues/21) regarding this topic, we have recieved several new reports from our users about this problem.
I understand that your plugin does not do anything special with the notifications, but we can consistently reproduce the problem using your page to blog conversion mechanism as follows:

1. User A creates a restricted page only they can view.
2. User B watches the entire space in which this page was created.
3. User A navigates to the restricted page and clicks "create" on the top bar. This will create a sub-page of the first one which will inherit all restrictions from its parent. No emails are sent at this point.
4. User A navigates to the new sub-page and clicks the three dots -> Convert page to blog. The "keep restrictions"-box is checked.
5. User B recieves an email about the new blog post. When clicking on the mail, confluence will (rightfully) say that this blog post is restricted and block access.
 
So yeah, we obviously would like to prevent step 5 from happening, as these emails can possibly contain sensible data.
Maybe you could help us figure this out by explaining what exactly happens when triggering "Convert page to blog"? Does it copy, paste as blog and then delete the page?
We'd appreciate as much insight as possible.

Let me know if you need to know anything else about our setup.

Kind regards,
Max

**Comment by chris-kent** [comment]
Hi Max,

I have had a quick look at the code, and I have a good idea why this is happenning.  I will look to provide an update in the next few days.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

sounds great, we're looking forward to it. Thanks for your efforts!

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

This was a little harder than I thought.  I don't know how to apply page restrictions before saving the blog, Confluence throws errors when I do this.  I'm not sure how Confluence itself does this and I can't find anything out there in developer help land.

So what I have done is disabled all Notifications when creating Blogs and Pages with my tool, I think this is easy, but unfortunately not testable in the developer environment I have :(

I have placed version 3.13 on the marketplace (untested), can you please download and test. If this works then the security issue you are having is fixed, however space watches will no longer get any notifications in future, which I think is a good compromise.  Let me know your thoughts.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,

I would like to close this, did the latest version help?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

we tested different scenarios with the new version. Here's our input:
The first good news is that the security problem seems to be fixed. Creating a blogpost from a restricted page with page-to-blog doesn't send an email anymore.
When creating a non-restricted blogpost using the addon, a mail gets sent out to all space-watchers ("User created a page"), which is also what we want. With the previous version, watchers would recieve two mails from that action ("User created a page" and "User created a blog post"), so that's definitely an improvement.

However, our issue with this solution is this: we have several users only watching the blog of a space (and not the space itself) using the button on the top right of the blog stream (https://confluence/pages/viewrecentblogposts.action?key=SPACE). These users will not recieve mails for any public blogposts anymore, since we rely on the page-to-blog macro for creating almost all of our blogs.
Do you have an idea for this? May it be possible for the plugin to check the page permissions beforehand, and then decide wether to send a mail depending if it's a public or restricted page/blogpost or not?

Thank you for all your help so far,
Max

**Comment by chris-kent** [comment]
Hi Max,

Yes I have been thinking about this too, and yes I will look into using the
page restrictions to suppress the blog email.  This won't be bullet proof,
as I can't pick and choose which users to send the email, I can only
suppress the email notification or not suppress them.

On another note, I am also reaching out to Atlassian to suppress the
initial Page email (that is useless with broken links).  So I hope to
remove those if Atlassian can assist.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,

I have implemented the change as discussed, but limited testing due to the development tools.  Can you please run some tests and let me know if this is now satisfactory?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

we've updated to 3.14. Unfortunately, the described issue still persists: we only get a mail when watching the whole space, not when just watching the blog.

I have voted for your Atlassian ticket, is there anything else we can do at this point?

**Comment by chris-kent** [comment]
OK,

Let me look at it again, maybe I have the logic wrong for the view restrictions.
I'll be on leave tomorrow, so I may not get to look at it until the new year.

On that note, Merry Christmas and Happy New Year.  Thanks for all your support this year and I hope I can get your Blogs working to your needs.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
sounds good to us. Take your time, you already have helped us out a lot this year. :-)
Thanks! Merry Christmas and best wishes to you too!

Cheers,
Max

**Comment by chris-kent** [comment]
Hi Max,

Can you please try this version? I played around with another save option, which may make a difference. I have not tested as before due to development environment not supporting emails....

If this works I'll put it on the marketplace.

Cheers
Chris
[confluence-blog-tools-3.15.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1578632/confluence-blog-tools-3.15.zip)

**Comment by maximilianpeter** [comment]
Hi Chris,

with this version, we are again getting two mails when watching a space (...created a site and ...created a blogpost)
Other than that, the plugin behaves exactly as we expect it to.

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

I just put a new version 3.15 on the marketplace. It is better than the version 3.15 you trialed from the attached above..

1. No emails sent for create Page.
2. Create blog now obeys restrictions/notifications, so the correct people should only be notified if restricted.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

unfortunately we're still getting two mails with this new version.. :/

We also get this stacktrace in atlassian-confluence.log whenever using the page-to-blog macro in a template and clicking "save": 
[blogtools_error.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1611125/blogtools_error.txt)

Maybe there is a correlation?

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

Yes this is related. 

Can you please turn on logging for my plugin and retry.

Then send me the contents of the log file before the error too.

I was able to get my test environment sending emails and I was quite confident of this solution.  I may have a timing problem to deal with.

Thanks
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

here is the new log: 
[blogtools_error_2.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1611210/blogtools_error_2.txt)

I have set 'net.kentcom.blogtools' on DEBUG, hope that's sufficient?

Cheers 
Max

**Comment by chris-kent** [comment]
Max,

Yes, that is great.  
I have another version to try, see attached.
Let me know if this works? ie. no error and also only one email notification.
Also, does the notification restriction work in this version? ie. only users with View permissions get the notification of new blogs?
Cheers
Chris
[confluence-blog-tools-3.15.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1611296/confluence-blog-tools-3.15.zip)

**Comment by maximilianpeter** [comment]
Hmm, still getting an error and 2 mails: 
[blogtools_error_3.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1611365/blogtools_error_3.txt)

A minor difference: now we get the "...created a blog" mail first and the "...created a page" mail second when creating a public page2blogpost. Before, it was the other way around.
The notification restriction is working fine, yes :)

-Max

**Comment by chris-kent** [comment]
Hmmm, I have another attempt, if this does not work, then back to the drawing board....

[confluence-blog-tools-3.16.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1611426/confluence-blog-tools-3.16.zip)

**Comment by maximilianpeter** [comment]
Sorry, still not working: 
[blogtools_error_4.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1614269/blogtools_error_4.txt)

The order of the mails is now reversed again.
Also, the result on the front-end is completely fine. The page gets converted to a blog and is then deleted as it should.

**Comment by chris-kent** [comment]
Ahh, I have this working nicely in my test environment....

I've made some minor mods, can you please try again.

If it fails, can you please send me the log again, there should be more tracing to help me debug this.

Also what version of Confluence do you have?

Cheers
Chris
[confluence-blog-tools-3.16,zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1614882/confluence-blog-tools-3.16.zip)

**Comment by maximilianpeter** [comment]
Here is the new log file:
[blogtools_error_5.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1615328/blogtools_error_5.txt)

We're testing on Confluence 5.10.3

Cheers,
Max

**Comment by chris-kent** [comment]
Hi Max,

I can confirm that my solution is broken with 5.10.3.  This is one of the version that Atlassian really buggered up my plugin, between 5.10.0 and 5.10.6.  I think that after 5.10.6, they fixed a few things and my plugin works better.

Are you planning on upgrading your Confluence soon?

If not, I can try to work out another solution to remove the duplicate emails?  I assume this is the only issue that you now face?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

I've just checked and noticed that our test environment is on 5.10.3 while production is on 5.10.8. Huh.
We'll upgrade our test confluence to 5.10.8 and report back. :)

Cheers,
Max

**Comment by maximilianpeter** [comment]
We've updated to 5.10.8, but still getting two mails and an error stacktrace.. 
[blogtools_error_6.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1622748/blogtools_error_6.txt)

Does the plugin work flawlessly in your instance? Do you not get the "Cannot add or update a child row: a foreign key constraint fails" errors? Maybe there is something wrong in our test database?

**Comment by chris-kent** [comment]
Hi Max,

I am now tearing my hair out, since I tried another confluence version I can't get the 6.6 version working. I must have had some hybrid system or something.

So, I have not fixed the duplicate emails yet and will give up for now as I am out of ideas.  I;ll come back to this soon with fresh eyes and maybe something will pop up.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

any news for this issue?

Cheers Max

**Comment by chris-kent** [comment]
Hi Max,

I am refactoring some code, but it is not helping and Atlassian have not replied to my issue either,
In Summary,I can't stop the email from being sent from the original page yet.

:(

Chris
